#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid
# Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true
do
echo "To infinity and beyond"
sleep 5
done
